os: windows
language: shell
arch: amd64

install:
  - choco install python --version=3.8.0 -y
  - C:\Python38\python.exe -m ensurepip
  - C:\Python38\python.exe -m pip install --upgrade pip

script:
  - C:\Python38\python.exe hello_world.py
